require: rubocop-rails

AllCops:
  SuggestExtensions: false
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - "bin/*"
    - "db/*"
    - "config/**/*"
    - "vendor/**/*"
    - "config.ru"
    - "Rakefile"
Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
